### ISSUE TITLE
Unable to find some referenced files causes exporter to stop/quit

### ISSUE THREAD

**Issue by geekpete** [tariquesani/lektor-exporter#1]
I think my wordpress blog is in a sad state at the moment, as I migrated it to new hosting quickly and it didn't go 100% well. One of the reasons I want to simplify my whole blog and get it static.

So seeing this error when using the exporter:

```
[Thu Aug 18 12:49:49.545712 2016] [:error] [pid 25697] [client x.x.x.x:55736] PHP Warning:  copy(/var/www/html/blog/wp-content/plugins/lektor-exporter/exports/wp-lektor-bac05d8e15d582293da82ab8efd5b2aa//blog/building-project-hamster-on-windows/projecthamster.png): failed to open stream: No such file or directory in /var/www/html/blog/wp-content/plugins/lektor-exporter/lektor-exporter.php on line 261, referer: https://geekpete.com/blog/wp-admin/
[Thu Aug 18 12:49:49.588703 2016] [:error] [pid 25697] [client x.x.x.x:55736] PHP Warning:  copy(/var/www/html/blog/wp-content/plugins/lektor-exporter/exports/wp-lektor-bac05d8e15d582293da82ab8efd5b2aa//blog/ssl-error-61-using-citrix-ica-client-on-linux/ssl-error-61.png): failed to open stream: No such file or directory in /var/www/html/blog/wp-content/plugins/lektor-exporter/lektor-exporter.php on line 261, referer: https://geekpete.com/blog/wp-admin/
```

**Comment by tariquesani** [comment]
Looks like some images are not getting copied. Should not be a problem with the content itself. Also the exporter runs much better from the command line because it does not encounter permission issues.

**Comment by geekpete** [comment]
So that seems to have produced an export for me, just doing:

```
php lektor-export-cli.php
```

OK so now just to stitch in the various content that has been generated...

**Comment by tariquesani** [comment]
You can now clone the blog project I have in another repo, drop your content in it and try lektor server in the directory. 

Hopefully it will serve without any major errors. Then you can start modifying the templates to suit your design.

**Comment by geekpete** [comment]
So for your next trick, a hugo/jekyll/pelican theme converter for Lektor?

So I'm using the quickstart blog project.
I found the blog post ordering wasn't working with the time next to the date for the pub_date field.
Once I removed the time, it ordered correctly.
Would be nice to have lektor utilise the time as well as the date, if you wanted to post more than one blog a day,etc.

**Comment by tariquesani** [comment]
The QuickStart project uses field type date. If you change it to datetime it should work. See https://github.com/tariquesani/blog/blob/master/models/blog-post.ini This is my model for wordpress exported content. Handles featured images, categories and tags

**Comment by geekpete** [comment]
Perfect thanks.
