### ISSUE TITLE
when exporting posts with featured image, the image is not added to the content folder of said post

### ISSUE THREAD

**Issue by torian257x** [tariquesani/lektor-exporter#2]
in the exported

`contents.lr`

i have

```
---
featured_image: rsz_1rsa-conference-news-coverage-2017-banner.jpg

```

this image is found in 

`wp-contents/uploads/2017/03`

it is in the exported folder, but it is not in the exported folder of the post

you get what I mean? there is only `contents.lr` the featured image is missing

**Comment by tariquesani** [comment]
This plugin does not copy images. This one does https://github.com/tariquesani/lektorify
