### ISSUE TITLE
HTML entities in article titles are not converted

### ISSUE THREAD

**Issue by talljosh** [tariquesani/lektor-exporter#3]
A number of my articles have titles with special characters such as apostrophes or smart quotes. After the export these special characters appear as HTML entities.

For instance, I have an article entitled <code>Things I’ve Learnt</code> but after the export it came out as <code>Things I&amp;#8217;ve Learnt</code>.

**Comment by tariquesani** [comment]
Thanks for the reports. If you can send a pull request I would be happy to merge. I don’t need this plugin anymore hence may not work on it anytime soon

**Comment by talljosh** [comment]
Ok, I'll have a stab at it and see how I go. I haven't done much PHP coding in a long time.
